version: '2'
services:

  backend:
    image: $IMAGE_DEV
    container_name: $CONTAINER_NAME
    ports: 
      - 8080:80
    #mem_limit: 300m
    volumes: 
      - ./../application:/application
    command: ["./node_modules/nodemon/bin/nodemon.js"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./../elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    #volumes:
     # - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
#  mysql:
#    image: mysql:5.7
#    container_name: $CONTAINER_DB_NAME
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234
#      MYSQL_DATABASE: flash_test
#    ports:
#      - 3306:3306
#    command: ['--sql-mode=NO_BACKSLASH_ESCAPES','--character-set-server=utf8', '--collation-server=utf8_spanish2_ci']
#    #volumes:
#    #  - ./container/mysql:/docker-entrypoint-initdb.d
